num = input('номер рейса: ')
name_rus = input('название авиакомпании (на русском языке): ')
name_eng = input('название авиакомпании (на английском языке): ')
city_rus = input('город прилета (на русском языке): ')
city_eng = input('город прилета (на английском языке): ')
print('Заканчивается посадка на рейс ' + num + ' авиакомпании ' + name_rus + ' до ' + city_rus)
print('This is the final boarding call for ' + name_eng + ' flight ' + num + ' to ' + city_eng)