song1 = input('Введите плей-лист папы: \n')
song2 = input()
song3 = input()
song4 = input()
song5 = input()
print('Плей-лист мамы: \n' + song5 + '\n' + song4 + '\n' + song3 + '\n' + song2 + '\n' + song1)
